version: "3.8"

services:
  bitcoin:
    image: ruimarinho/bitcoin-core
    container_name: ordit-bitcoin
    ports:
      - ${RPC_PORT}:${RPC_PORT} # regtest:18443 testnet:18332 mainnet:8332
    volumes:
      - ./.data/bitcoin:/home/bitcoin/.bitcoin
    command: -printtoconsole
      -txindex=1
      -testnet=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=${RPC_USER}
      -rpcpassword=${RPC_PASSWORD}
      -blocknotify='curl http://host.docker.internal:3031/hooks/bitcoin?block=%s'
