version: "3.8"

services:
  bitcoin:
    image: ruimarinho/bitcoin-core
    container_name: bitcoin-regtest
    restart: always
    ports:
      - 18443:18443 # regtest:18443 testnet:18332 mainnet:8332
    volumes:
      - ./.bitcoin:/home/bitcoin/.bitcoin
    command: 
      -printtoconsole
      -txindex=1
      -regtest=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=bitcoin
      -rpcpassword=bitcoin
      -blocknotify='curl http://127.0.0.1:3031/hooks/bitcoin?block=%s' # target trinity watcher
